# Generated by Django 4.2.5 on 2023-10-03 21:04

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serverLogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotewindowsserver',
            name='credentials',
            field=fernet_fields.fields.EncryptedCharField(max_length=500),
        ),
    ]
