# Generated by Django 4.2.5 on 2023-10-03 21:37

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serverLogs', '0003_remove_remotewindowsserver_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotewindowsserver',
            name='credentials',
            field=fernet_fields.fields.EncryptedCharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
