# Generated by Django 4.2.5 on 2023-10-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverLogs', '0004_remotewindowsserver_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_query', models.TextField()),
            ],
        ),
    ]
