# Generated by Django 4.2.5 on 2025-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverLogs', '0006_pacscore_server_type_remotelinuxserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotelinuxserver',
            name='ssh_key',
        ),
        migrations.AddField(
            model_name='remotelinuxserver',
            name='ssh_key_path',
            field=models.CharField(default='d:/web/JSF/webserverMaintenance/id_rsa', help_text='Path to the SSH private key file', max_length=500),
        ),
    ]
