# Generated by Django 4.2.5 on 2023-09-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditquery',
            name='multiple_queries',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('parent_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_queries.auditquery')),
            ],
        ),
    ]
