# Generated by Django 4.2.5 on 2023-09-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_queries', '0002_auditquery_multiple_queries_subquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquery',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
