# Generated by Django 4.2.5 on 2023-09-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0006_savedquery_query_type'),
        ('audit_queries', '0003_subquery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquery',
            name='database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oracleQuery.friendlydbname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subquery',
            name='parent_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_queries', to='audit_queries.auditquery'),
        ),
    ]
