# Generated by Django 4.2.5 on 2023-10-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_queries', '0004_subquery_database_alter_subquery_parent_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditquery',
            name='preliminary_db',
            field=models.CharField(blank=True, help_text='Database to run the preliminary query against', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditquery',
            name='preliminary_query',
            field=models.TextField(blank=True, help_text='SQL query to fetch extra data needed for the main query', null=True),
        ),
        migrations.AddField(
            model_name='auditquery',
            name='requires_preliminary',
            field=models.BooleanField(default=False),
        ),
    ]
