# Generated by Django 4.2.5 on 2023-10-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0006_savedquery_query_type'),
        ('audit_queries', '0005_auditquery_preliminary_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditquery',
            name='preliminary_db',
            field=models.ForeignKey(blank=True, help_text='Database to run the preliminary query against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preliminary_queries', to='oracleQuery.friendlydbname'),
        ),
    ]
