# Generated by Django 4.2.5 on 2023-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_queries', '0006_alter_auditquery_preliminary_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_audit_queries', 'Can use audit queries')],
            },
        ),
    ]
