# Generated by Django 4.2.5 on 2023-10-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_applink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_JSF', 'Can use JSF')],
            },
        ),
    ]
