# Generated by Django 4.2.5 on 2023-10-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_apppermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='required_permission',
            field=models.CharField(default=1, help_text='Permission required to access this app.', max_length=255),
            preserve_default=False,
        ),
    ]
