# Generated by Django 4.2.5 on 2024-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroImageBridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_user', models.CharField(max_length=255)),
                ('xero_password', models.CharField(max_length=255)),
            ],
        ),
    ]
