# Generated by Django 4.2.5 on 2024-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroImageBridge', '0002_xeroconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroconfig',
            name='xero_domain',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xeroconfig',
            name='xero_server',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
