# Generated by Django 4.2.5 on 2024-09-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroImageBridge', '0003_xeroconfig_xero_domain_xeroconfig_xero_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroconfig',
            name='display_vars',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xeroconfig',
            name='query_constraints',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
