# Generated by Django 4.2.5 on 2024-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroImageBridge', '0005_xeroconfig_ticket_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroconfig',
            name='xero_server_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
