# Generated by Django 4.2.5 on 2023-10-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserverMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_webserverMaintenance', 'Can use Webserver Maintenance')],
            },
        ),
    ]
