# Generated by Django 4.2.5 on 2024-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEIWorkstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_move_ei_workstations', 'Can use Move EI Workstations')],
            },
        ),
    ]
