# Generated by Django 4.2.5 on 2024-10-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timezone_updater', '0004_apppermissions'),
        ('updatecontact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='ei_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timezone_updater.eisystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitygroup',
            name='ei_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timezone_updater.eisystem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
