# Generated by Django 4.2.5 on 2024-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatecontact', '0002_facility_ei_system_facility_facility_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_updatecontact', 'Can use Contact Updater')],
            },
        ),
    ]
