# Generated by Django 4.2.5 on 2025-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatecontact', '0004_eiuser_eiuserfacilityassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiuser',
            name='facility_groups',
            field=models.ManyToManyField(blank=True, to='updatecontact.facilitygroup'),
        ),
    ]
