# Generated by Django 4.2.5 on 2025-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatecontact', '0005_eiuser_facility_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitygroup',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
