# Generated by Django 4.2.5 on 2023-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OracleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteOracleServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=1521)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
    ]
