# Generated by Django 4.2.5 on 2023-09-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteOracleServer',
        ),
    ]
