# Generated by Django 4.2.5 on 2023-09-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0002_delete_remoteoracleserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.TextField()),
                ('_variables', models.TextField(default='[]')),
            ],
        ),
    ]
