# Generated by Django 4.2.5 on 2023-09-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0003_savedquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OracleQuery',
        ),
    ]
