# Generated by Django 4.2.5 on 2023-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0004_delete_oraclequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyDBName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_alias', models.CharField(max_length=50, unique=True)),
                ('friendly_name', models.CharField(max_length=100)),
            ],
        ),
    ]
