# Generated by Django 4.2.5 on 2023-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleQuery', '0005_friendlydbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='query_type',
            field=models.CharField(choices=[('impax', 'Impax'), ('ei', 'EI')], default='impax', max_length=5),
        ),
    ]
