# Generated by Django 4.2.5 on 2024-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ei_fqdn', models.CharField(max_length=255)),
                ('ei_user', models.CharField(max_length=255)),
                ('ei_password', models.CharField(max_length=255)),
            ],
        ),
    ]
