# Generated by Django 4.2.5 on 2024-02-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timezone_updater', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalSystem',
            new_name='EISystems',
        ),
    ]
