# Generated by Django 4.2.5 on 2024-02-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timezone_updater', '0002_rename_externalsystem_eisystems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EISystems',
            new_name='EISystem',
        ),
    ]
