# Generated by Django 4.2.5 on 2024-02-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone_updater', '0003_rename_eisystems_eisystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('use_timezone_updater', 'Can use TimeZone Updater')],
            },
        ),
    ]
